version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: malisha-edu-db
    environment:
      POSTGRES_DB: malisha_edu_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - malisha-edu-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: malisha-edu-backend
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: malisha_edu_db
      DB_USER: postgres
      DB_PASSWORD: Asif@10018
      JWT_SECRET: Asif@10018
      JWT_EXPIRES_IN: 7d
      R2_ACCOUNT_ID: d64e7978ed801f4ac433d221e0cb0649
      R2_ACCESS_KEY_ID: 15a24647194a77aad11f185c00970dd0
      R2_SECRET_ACCESS_KEY: c1e696264668b40b87b1f6e2ea68b6639909f115d468c5a337088569ad5de211
      R2_BUCKET_NAME: malisha-edu-storage
      R2_PUBLIC_URL: https://pub-9c8141e374374e25a5892600464a26e3.r2.dev
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - malisha-edu-network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: malisha-edu-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - malisha-edu-network
    restart: unless-stopped

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: malisha-edu-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - malisha-edu-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  malisha-edu-network:
    driver: bridge
