[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'cd backend && npm ci --only=production',
  'cd frontend && npm ci && npm run build'
]

[phases.build]
cmds = [
  'cd backend && npm run migrate'
]

[start]
cmd = 'cd backend && npm start'

[variables]
NODE_ENV = 'production'
PORT = '5000'
