exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('programs').del();
  
  // Inserts seed entries
  await knex('programs').insert([
    {
      id: 1,
      university_id: 1,
      name: 'Computer Science',
      english_name: 'Computer Science',
      description: 'A comprehensive program covering computer science fundamentals and advanced topics.',
      degree_level: 'master',
      language: 'english',
      duration_years: 2,
      tuition_fee: 30000,
      accommodation_fee: 12000,
      scholarship_amount: 30000,
      scholarship_type: 'full',
      scholarship_description: 'Full scholarship covering tuition, accommodation, and living expenses.',
      application_deadline: '2024-03-15',
      intake_date: '2024-09-01',
      intake_season: 'autumn',
      accepts_minors: false,
      min_age: 18,
      max_age: 35,
      min_gpa: 3.0,
      min_ielts_score: 6.5,
      additional_requirements: 'Bachelor degree in Computer Science or related field',
      is_featured: true,
      is_active: true
    },
    {
      id: 2,
      university_id: 2,
      name: 'International Business',
      english_name: 'International Business',
      description: 'A program designed to prepare students for global business careers.',
      degree_level: 'bachelor',
      language: 'bilingual',
      duration_years: 4,
      tuition_fee: 25000,
      accommodation_fee: 10000,
      scholarship_amount: 15000,
      scholarship_type: 'partial',
      scholarship_description: 'Partial scholarship covering 60% of tuition fees.',
      application_deadline: '2024-04-30',
      intake_date: '2024-09-01',
      intake_season: 'autumn',
      accepts_minors: true,
      min_age: 17,
      max_age: 25,
      min_gpa: 2.8,
      min_ielts_score: 6.0,
      additional_requirements: 'High school diploma or equivalent',
      is_featured: true,
      is_active: true
    },
    {
      id: 3,
      university_id: 3,
      name: 'Chinese Language Program',
      english_name: 'Chinese Language Program',
      description: 'Intensive Chinese language learning program for international students.',
      degree_level: 'language',
      language: 'chinese',
      duration_months: 12,
      tuition_fee: 15000,
      accommodation_fee: 8000,
      scholarship_amount: 15000,
      scholarship_type: 'full',
      scholarship_description: 'Full scholarship covering all program costs.',
      application_deadline: '2024-02-28',
      intake_date: '2024-03-01',
      intake_season: 'spring',
      accepts_minors: true,
      min_age: 16,
      max_age: 50,
      additional_requirements: 'No prior Chinese language knowledge required',
      is_featured: true,
      is_active: true
    },
    {
      id: 4,
      university_id: 4,
      name: 'Engineering',
      english_name: 'Engineering',
      description: 'Advanced engineering program with focus on innovation and research.',
      degree_level: 'phd',
      language: 'english',
      duration_years: 4,
      tuition_fee: 35000,
      accommodation_fee: 15000,
      scholarship_amount: 35000,
      scholarship_type: 'full',
      scholarship_description: 'Full scholarship with research stipend.',
      application_deadline: '2024-05-15',
      intake_date: '2024-09-01',
      intake_season: 'autumn',
      accepts_minors: false,
      min_age: 22,
      max_age: 40,
      min_gpa: 3.2,
      min_ielts_score: 7.0,
      additional_requirements: 'Master degree in Engineering or related field, research proposal required',
      is_featured: true,
      is_active: true
    },
    {
      id: 5,
      university_id: 5,
      name: 'Medicine',
      english_name: 'Medicine',
      description: 'Comprehensive medical program for international students.',
      degree_level: 'master',
      language: 'chinese',
      duration_years: 3,
      tuition_fee: 40000,
      accommodation_fee: 12000,
      scholarship_amount: 20000,
      scholarship_type: 'partial',
      scholarship_description: 'Partial scholarship covering 50% of tuition fees.',
      application_deadline: '2024-03-31',
      intake_date: '2024-09-01',
      intake_season: 'autumn',
      accepts_minors: false,
      min_age: 20,
      max_age: 35,
      min_gpa: 3.0,
      min_hsk_level: 4,
      additional_requirements: 'Bachelor degree in Medicine or related field, HSK Level 4 or above',
      is_featured: true,
      is_active: true
    },
    {
      id: 6,
      university_id: 6,
      name: 'ISSP Program',
      english_name: 'International Student Scholarship Program',
      description: 'Special scholarship program for outstanding international students.',
      degree_level: 'bachelor',
      language: 'english',
      duration_years: 4,
      tuition_fee: 20000,
      accommodation_fee: 8000,
      scholarship_amount: 20000,
      scholarship_type: 'full',
      scholarship_description: 'Full scholarship covering tuition and accommodation.',
      application_deadline: '2024-04-15',
      intake_date: '2024-09-01',
      intake_season: 'autumn',
      accepts_minors: true,
      min_age: 17,
      max_age: 25,
      min_gpa: 3.5,
      min_ielts_score: 6.5,
      additional_requirements: 'Outstanding academic record, leadership experience preferred',
      is_featured: true,
      is_active: true
    }
  ]);
};
